# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8733a3d5ca93a92760158721f6f5795495d4cadcf3ed82476b3f36b5ad822ce3d6b5fcb1d7801eb5a0bd5cd6091f5a167394c3b212a27c93e15f5de8a86b5ef8

test:
  secret_key_base: 8f76001dcf596dfd54debfa83f336cbae613f97dda990523e33599d82971712bba47aca75a3bee4db371d7779feaa28a14c6d65dd993216f6487db70fd4951e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
